spring.application.name=CartService
server.port=8083

spring.datasource.url=jdbc:h2:mem:cartdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.instances.inventoryService.register-metrics=true
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=10
resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=5000ms
resilience4j.circuitbreaker.instances.inventoryService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.inventoryService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.inventoryService.automatic-transition-from-open-to-half-open-enabled=true

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always


# Define the location for log files
#logging.file.name=C://Users/somyagupta01/myProjects/microservices/logs/zion.log


logging.file.name=/logs/zion.log
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Send logs to Logstash
logging.logback.appender.logstash.destination=localhost:5044